SportsStore.WebUI/Controllers/OrderController.cs
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Data;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class OrderController : Controller
    {
        public int PageSize = 4;
        IOrderRepository _orderRepository;

        public OrderController(IOrderRepository orderRepository)
        {
            _orderRepository = orderRepository;
        }

        public ActionResult Index(int Id,int? page = 1)
        {
            var model = new ListViewModel<Order>
            {
                Elements = _orderRepository.Orders.OrderBy(o=>o.Date)
                                                  .Where(o=>o.UserId == Id)
                                                  .Skip((page.Value - 1) * PageSize)
                                                  .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page.Value,
                    ItemsPerPage = PageSize,
                    TotalItems = _orderRepository.Orders.Count()
                }
            };
            return View(model);
        }

        public ViewResult List(int page = 1)
        {
            var model = new ListViewModel<Order>
            {
                Elements = _orderRepository.Orders.OrderBy(p => p.Date)
                                      .Skip((page - 1) * PageSize)
                                      .Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _orderRepository.Orders.Count()
                }
            };
            return View(model);
        }

        public ViewResult Edit(int Id)
        {
            var model = _orderRepository.Orders.FirstOrDefault(p => p.Id == Id);
            ViewBag.Statues = new SelectList(_orderRepository.Statues, "Id", "Name", model?.StatusId);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Order order)
        {
            if (!ModelState.IsValid) return View(order);

            _orderRepository.SaveOrder(order);
            TempData["message"] = $"Zapisano {order.Name}";
            return RedirectToAction("List");
        }

    }
}

SportsStore.WebUI/Controllers/OrderListController.cs
using System.Linq;
using System.Web.Mvc;
using Rotativa;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Controllers
{
    public class OrderListController : Controller
    {
        IOrderListRepository _orderListRepository;

        public OrderListController(IOrderListRepository orderListRepository)
        {
            _orderListRepository = orderListRepository;
        }

        public ActionResult Index(int Id)
        {
            var model = _orderListRepository.OrdersList.Where(ol => ol.OrderId == Id);
            return View(model);
        }

        public ActionResult CreatePdf(int Id)
        {
            var model = _orderListRepository.OrdersList.Where(ol => ol.OrderId == Id);
            return View(model);
        }

        public ActionResult PrintInvoice(int Id)
        {
            return new ActionAsPdf("CreatePdf",new {Id = Id})
            {
                FileName = "Faktura.pdf"
            };
        }
    }
}

SportsStore.WebUI/Views/Order/Edit.cshtml
@using SportsStore.Domain.Data
@model Order

@{
    ViewBag.Title = $"Edycja: {Model.Name}";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel">
    <div class="panel-heading">
        <h3>Edycja @Model.Name</h3>
    </div>
    @using (Html.BeginForm("Edit", "Order", FormMethod.Post))
    {
        <div class="panel-body">
            @Html.HiddenFor(x => x.Id)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "Id":
                    case "Status":
                    case "Name":
                    case "User":
                    case "OrderLists":
                    case "Date":
                    case "StatusId":
                    case "UserId":
                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            @Html.HiddenFor(p=>p.Name)
            @Html.HiddenFor(p=>p.UserId)
            <div class="form-group">
                <label>Status</label>
                @Html.DropDownListFor(p=>p.StatusId, (SelectList)ViewBag.Statues
                                      , "Wybierz status", new { @class = "form-control" })
                @Html.ValidationMessageFor(m=>m.StatusId)
            </div>

        </div>
        <div class="panel-footer">
            <input type="submit" value="Zapisz" class="btn btn-primary" />
            @Html.ActionLink("Wróć do listy", "Index", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

SportsStore.WebUI/Views/Order/Index.cshtml
@using SportsStore.Domain.Data
@using SportsStore.WebUI.Models
@model ListViewModel<Order>
@{
    Layout = "~/Views/Shared/_UserPanelLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Zamówienia</h2>
        @Html.ActionLink("Cofnij sie do panelu użytkownika", "Login", "Account", null, new { @class = "btn btn-primary" })
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th>Nazwa</th>
                <th>Data</th>
                <th>Status</th>
                <th>Szczegóły</th>
                <th>Faktura PDF</th>
            </tr>
            @foreach (var item in Model.Elements)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Date</td>
                    <td>@item.Status.Name</td>
                    <td>@Html.ActionLink("Szczegóły", "Index", "OrderList", new {Id = item.Id}, new { @class = "btn btn-success" })</td>
                    <td>@Html.ActionLink("Faktura", "PrintInvoice", "OrderList", new { Id = item.Id }, new { @class = "btn btn-success" })</td>
                </tr>
            }
        </table>
        <div class="btn-group pull-right">
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("Index", new { page = x}))
        </div>
    </div>
</div>

SportsStore.WebUI/Views/Order/List.cshtml
@using SportsStore.Domain.Data
@using SportsStore.WebUI.Models
@model ListViewModel<Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Zamówienia</h2>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th>Nazwa</th>
                <th>Data</th>
                <th>Status</th>
            </tr>
            @foreach (var item in Model.Elements)
            {
                <tr>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.Id })</td>
                    <td>@item.Date</td>
                    <td>@item.Status.Name</td>
                </tr>
            }
        </table>
        <div class="btn-group pull-right">
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x }))
        </div>
    </div>
</div>