SportsStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Data;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{

    public class CartController : Controller
    {
        IProductRepository _repository;
        IOrderProcessor _orderProcessor;
        IUserRepository _userRepository;

        public CartController(IProductRepository repository, IOrderProcessor orderProcessor, IUserRepository userRepository)
        {
            _repository = repository;
            _orderProcessor = orderProcessor;
            _userRepository = userRepository;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddtoCart(Cart cart, int Id, string returnUrl, int quantity)
        {
            var product = _repository.Products.FirstOrDefault(p => p.Id == Id);

            if (product != null)
                cart.AddItem(product, quantity);

            return RedirectToAction("Index", new { returnUrl });
        }

        public ActionResult AddOneToCart(Cart cart, int Id, string returnUrl)
        {
            var product = _repository.Products.FirstOrDefault(p => p.Id == Id);
            if (product != null)
                cart.AddItem(product, 1);

            return RedirectToAction("Index", new { returnUrl });
        }

        public ActionResult RemoveOneFromCart(Cart cart, int Id, string returnUrl)
        {
            var product = _repository.Products.FirstOrDefault(p => p.Id == Id);
            if (product != null)
                cart.RemoveOne(product);

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int Id, string returnUrl)
        {
            var product = _repository.Products.FirstOrDefault(p => p.Id == Id);

            if (product != null)
                cart.RemoveLine(product);

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout(Cart cart)
        {
            if (!cart.Lines.Any())
                ModelState.AddModelError("", "Koszyk jest pusty");

            if (!ModelState.IsValid) return View();

            var user = _userRepository.Users.FirstOrDefault(u => u.Email == HttpContext.User.Identity.Name);
            _orderProcessor.ProcessOrder(cart, user);
            cart.Clear();
            return View("Completed");
        }
    }
}

SportsStore.WebUI/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Data;

namespace SportsStore.WebUI.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class CityController : Controller
    {
        ICityRepository _repository;

        public CityController(ICityRepository repository)
        {
            _repository = repository;
        }

        public ViewResult Index()
        {
            return View(_repository.Cities);
        }

        public ViewResult Create()
        {
            return View("Edit", new City());
        }

        public ViewResult Edit(int Id)
        {
            City city = _repository.Cities.FirstOrDefault(p => p.Id == Id);
            return View(city);
        }

        [HttpPost]
        public ActionResult Edit(City city)
        {
            if (!ModelState.IsValid) return View(city);

            _repository.SaveCity(city);
            TempData["message"] = $"Zapisano {city.Name}";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            City deletedCity = _repository.DeleteCity(Id);
            if (deletedCity != null)
                TempData["message"] = $"Usunięto {deletedCity.Name}";

            return RedirectToAction("Index");
        }
    }
}

SportsStore.WebUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Controllers
{

	public class NavController : Controller
	{
		ICategoryRepository _repository;

		public NavController(ICategoryRepository repository)
		{
			_repository = repository;
		}

		public PartialViewResult Menu(string category = null)
		{
			ViewBag.SelectedCategory = category;
			IEnumerable<string> categories = _repository.Categories.Select(c => c.Name)
																   .Distinct()
																   .OrderBy(c => c);
			return PartialView("FlexMenu",categories);
		}
	}

}

SportsStore.WebUI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Data;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserController : Controller
    {
        IUserRepository _repository;
        public int PageSize = 4;

        public UserController(IUserRepository repository)
        {
            _repository = repository;

        }
        [Authorize(Roles = "Administrator")]
        public ViewResult Index(int page = 1)
        {
            var model = new ListViewModel<User>
            {
                Elements = _repository.Users.OrderBy(p => p.Id)
                                      .Skip((page - 1) * PageSize)
                                      .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _repository.Users.Count()
                }
            };
            return View(model);
        }
        public ViewResult Create()
        {
            ViewBag.Addresses = new SelectList(_repository.Addresses, "Id", "Street");
            ViewBag.Roles = new SelectList(_repository.Roles, "Id", "Name");
            return View("Edit", new User());
        }

        public ViewResult Edit(int Id)
        {
            User user = _repository.Users.FirstOrDefault(p => p.Id == Id);
            ViewBag.Addresses = new SelectList(_repository.Addresses, "Id", "FullName", user?.AddressId);
            ViewBag.Roles = new SelectList(_repository.Roles, "Id", "Name", user?.RoleId);
            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(User user)
        {
            if (!ModelState.IsValid) return View(user);

            _repository.SaveUser(user);
            TempData["message"] = $"Zapisano {user.FirstName}";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            User deletedUser = _repository.DeleteUser(Id);
            if (deletedUser != null)
                TempData["message"] = $"Usunięto {deletedUser.FirstName}";

            return RedirectToAction("Index");
        }
    }
}

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link rel="stylesheet" href="~/Content/bootstrap.css"/>
    <link rel="stylesheet" href="~/Content/bootstrap-theme.css"/>
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css"/>
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <ul class="nav navbar-nav navbar-right">
        @{
            if (HttpContext.Current.User.Identity.IsAuthenticated)
            {
                var userName = HttpContext.Current.User.Identity.Name;
                <li> @Html.ActionLink(userName, "Login", "Account", null, new { @class = "navbar-btn" })</li>
                <li>@Html.ActionLink("Wyloguj", "Logout", "Account", null, new { @class = "navbar-btn" })</li>
            }
            else
            {
                <li>
                    <a href="@Url.Action("Register", "Account")" class="nav navbar-btn">
                        Rejestracja
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Login", "Account")" class="nav navbar-btn">
                        Zaloguj
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                    </a>
                </li>
            }
        }
    </ul>
       
    <ul class="nav navbar-nav navbar-left">
        <li><a class="navbar-brand" href="#">Panel Administracyjny</a></li>
        <li>@Html.ActionLink("Produkty", "Index", "Product", null, new { @class = "nav navbar-btn" })</li>
        <li>@Html.ActionLink("Kategorie produktów", "Index", "Category", null, new { @class = "nav navbar-btn" })</li>
        <li>@Html.ActionLink("Role", "Index", "Role", null, new { @class = "nav navbar-btn" })</li>
        <li>@Html.ActionLink("Użytkownicy", "Index", "User", null, new { @class = "nav navbar-btn" })</li>
        <li>@Html.ActionLink("Adresy", "Index", "Addres", null, new { @class = "nav navbar-btn" })</li>
        <li>@Html.ActionLink("Miasta", "Index", "City", null, new { @class = "nav navbar-btn" })</li>
        <li>@Html.ActionLink("Status", "Index", "Status", null, new { @class = "nav navbar-btn" })</li>
        <li>@Html.ActionLink("Zamówienia", "List", "Order", null, new { @class = "nav navbar-btn" })</li>
    </ul>
            
       
       
    

</nav>
<br/><br/><br/>
<div>
    @if (TempData["message"] != null) {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width initial-scale=1.0"/>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css"/>
	<script  src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	<script  src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js" ></script>
	<title>@ViewBag.Title</title>
</head>
<body>
<div data-role="page" id="page1">
	<div data-theme="a" data-role="header" data-position="fixed">
		<h3>SportsStore</h3>
		@Html.Action("Menu","Nav")
	</div>
</div>
<div data-role="content">
	<ul data-role="listview" data-divider-theme="b" data-inset="false">
		@RenderBody()
	</ul>
</div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width initial-scale=1.0"/>
    <link rel="stylesheet" href="~/Content/bootstrap.css"/>
    <link rel="stylesheet" href="~/Content/bootstrap-theme.css"/>
    <link rel="stylesheet" href="~/Content/Site.css"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <a class="navbar-brand" href="#">
        <span class="hidden-xs">Sklep sportowy</span>
        <div class="visible-xs">Sklep</div>
        <div class="visible-xs">Sportowy</div>
    </a>
    <div>
        @using (Html.BeginForm("FilteredList", "Product",FormMethod.Post,new {@class= "navbar-form navbar-left" })){
            <div class="form-group">
                <input name="search" type="text" class="form-control" placeholder="Szukaj">
            </div>
            <input type="submit" class="btn btn-default" value="Szukaj"/>
        }
    </div>
    <ul class="nav navbar-nav navbar-right">
        @{
            if (HttpContext.Current.User.Identity.IsAuthenticated)
            {
                var email = "Jesteś zalogowany jako:" + HttpContext.Current.User.Identity.Name;
                <li> @Html.ActionLink(email, "Login", "Account", null, new { @class = "navbar-btn" })</li>
                <li>@Html.ActionLink("(wyloguj)", "Logout", "Account", null, new { @class = "navbar-btn" })</li>
            }
            else
            {
                <li>
                    <a href="@Url.Action("Register", "Account")" class="nav navbar-btn">
                        Rejestracja
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
                </li>
                <li>
                    <a href="@Url.Action("Login", "Account")" class="nav navbar-btn ">
                        Zaloguj
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span></a>
                </li>
                }
        }
    </ul>
    @if (HttpContext.Current.User.IsInRole("Klient")){
        @Html.Action("Summary", "Cart")
    }
</div>
    <br /><br /><br /><br />
<div class="visible-xs">
    <br /><br /><br />
    @Html.Action("Menu", "Nav", new { horizontalLayout = true })
</div>
<div class="row panel">
    <div id="categories" class="col-sm-3 hidden-xs">
        @Html.Action("Menu", "Nav")
    </div>
    <div class="col-xs-12 col-sm-8">
        @RenderBody()
    </div>
</div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_UserPanelLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width initial-scale=1.0" />
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/bootstrap-theme.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">Sklep sportowy</span>
            <div class="visible-xs">Sklep</div>
            <div class="visible-xs">Sportowy</div>
        </a>
        <ul class="nav navbar-nav navbar-right">
            @{
                if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    var userName = "Jesteś zalogowany jako:" + HttpContext.Current.User.Identity.Name;
                    <li> @Html.ActionLink(userName, "Login", "Account", null, new { @class = "navbar-btn" })</li>
                    <li>@Html.ActionLink("(wyloguj)", "Logout", "Account", null, new { @class = "navbar-btn" })</li>
                }
                else
                {
                    <li>
                        <a href="@Url.Action("Register", "Account")" class="nav navbar-btn">
                            Rejestracja
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Login", "Account")" class="nav navbar-btn">
                            Zaloguj
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                        </a>
                    </li>
                }
            }
        </ul>
    </div>
<div class="container">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</div>
</body>
</html>